name: self-lensing
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.7
  - pip >= 21.0.0
  - numpy >= 1.16
  - astropy >= 4.0
  - matplotlib >= 3.3.2
  - jupyterlab
  - jupyterlab_widgets
  - jupyter
  - ipython
  - ipywidgets
  - pip:
    - lightkurve